/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,md,mdx}",
    "./docs/**/*.{js,ts,jsx,tsx,md,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--zhiman-background))",
        foreground: "hsl(var(--zhiman-foreground))",
        // 基础颜色系统
        red: {
          50: "hsl(var(--zhiman-red-50))",
          100: "hsl(var(--zhiman-red-100))",
          200: "hsl(var(--zhiman-red-200))",
          300: "hsl(var(--zhiman-red-300))",
          400: "hsl(var(--zhiman-red-400))",
          500: "hsl(var(--zhiman-red-500))",
          600: "hsl(var(--zhiman-red-600))",
          700: "hsl(var(--zhiman-red-700))",
          800: "hsl(var(--zhiman-red-800))",
          900: "hsl(var(--zhiman-red-900))",
          950: "hsl(var(--zhiman-red-950))",
        },
        green: {
          50: "hsl(var(--zhiman-green-50))",
          100: "hsl(var(--zhiman-green-100))",
          200: "hsl(var(--zhiman-green-200))",
          300: "hsl(var(--zhiman-green-300))",
          400: "hsl(var(--zhiman-green-400))",
          500: "hsl(var(--zhiman-green-500))",
          600: "hsl(var(--zhiman-green-600))",
          700: "hsl(var(--zhiman-green-700))",
          800: "hsl(var(--zhiman-green-800))",
          900: "hsl(var(--zhiman-green-900))",
          950: "hsl(var(--zhiman-green-950))",
        },
        blue: {
          50: "hsl(var(--zhiman-blue-50))",
          100: "hsl(var(--zhiman-blue-100))",
          200: "hsl(var(--zhiman-blue-200))",
          300: "hsl(var(--zhiman-blue-300))",
          400: "hsl(var(--zhiman-blue-400))",
          500: "hsl(var(--zhiman-blue-500))",
          600: "hsl(var(--zhiman-blue-600))",
          700: "hsl(var(--zhiman-blue-700))",
          800: "hsl(var(--zhiman-blue-800))",
          900: "hsl(var(--zhiman-blue-900))",
          950: "hsl(var(--zhiman-blue-950))",
        },
        yellow: {
          50: "hsl(var(--zhiman-yellow-50))",
          100: "hsl(var(--zhiman-yellow-100))",
          200: "hsl(var(--zhiman-yellow-200))",
          300: "hsl(var(--zhiman-yellow-300))",
          400: "hsl(var(--zhiman-yellow-400))",
          500: "hsl(var(--zhiman-yellow-500))",
          600: "hsl(var(--zhiman-yellow-600))",
          700: "hsl(var(--zhiman-yellow-700))",
          800: "hsl(var(--zhiman-yellow-800))",
          900: "hsl(var(--zhiman-yellow-900))",
          950: "hsl(var(--zhiman-yellow-950))",
        },
        purple: {
          50: "hsl(var(--zhiman-purple-50))",
          100: "hsl(var(--zhiman-purple-100))",
          200: "hsl(var(--zhiman-purple-200))",
          300: "hsl(var(--zhiman-purple-300))",
          400: "hsl(var(--zhiman-purple-400))",
          500: "hsl(var(--zhiman-purple-500))",
          600: "hsl(var(--zhiman-purple-600))",
          700: "hsl(var(--zhiman-purple-700))",
          800: "hsl(var(--zhiman-purple-800))",
          900: "hsl(var(--zhiman-purple-900))",
          950: "hsl(var(--zhiman-purple-950))",
        },
        pink: {
          50: "hsl(var(--zhiman-pink-50))",
          100: "hsl(var(--zhiman-pink-100))",
          200: "hsl(var(--zhiman-pink-200))",
          300: "hsl(var(--zhiman-pink-300))",
          400: "hsl(var(--zhiman-pink-400))",
          500: "hsl(var(--zhiman-pink-500))",
          600: "hsl(var(--zhiman-pink-600))",
          700: "hsl(var(--zhiman-pink-700))",
          800: "hsl(var(--zhiman-pink-800))",
          900: "hsl(var(--zhiman-pink-900))",
          950: "hsl(var(--zhiman-pink-950))",
        },
        orange: {
          50: "hsl(var(--zhiman-orange-50))",
          100: "hsl(var(--zhiman-orange-100))",
          200: "hsl(var(--zhiman-orange-200))",
          300: "hsl(var(--zhiman-orange-300))",
          400: "hsl(var(--zhiman-orange-400))",
          500: "hsl(var(--zhiman-orange-500))",
          600: "hsl(var(--zhiman-orange-600))",
          700: "hsl(var(--zhiman-orange-700))",
          800: "hsl(var(--zhiman-orange-800))",
          900: "hsl(var(--zhiman-orange-900))",
          950: "hsl(var(--zhiman-orange-950))",
        },
        gray: {
          50: "hsl(var(--zhiman-gray-50))",
          100: "hsl(var(--zhiman-gray-100))",
          200: "hsl(var(--zhiman-gray-200))",
          300: "hsl(var(--zhiman-gray-300))",
          400: "hsl(var(--zhiman-gray-400))",
          500: "hsl(var(--zhiman-gray-500))",
          600: "hsl(var(--zhiman-gray-600))",
          700: "hsl(var(--zhiman-gray-700))",
          800: "hsl(var(--zhiman-gray-800))",
          900: "hsl(var(--zhiman-gray-900))",
          950: "hsl(var(--zhiman-gray-950))",
        },
        primary: {
          DEFAULT: "hsl(var(--zhiman-primary))",
          foreground: "hsl(var(--zhiman-primary-foreground))",
          50: "hsl(var(--zhiman-primary-50))",
          100: "hsl(var(--zhiman-primary-100))",
          200: "hsl(var(--zhiman-primary-200))",
          300: "hsl(var(--zhiman-primary-300))",
          400: "hsl(var(--zhiman-primary-400))",
          500: "hsl(var(--zhiman-primary-500))",
          600: "hsl(var(--zhiman-primary-600))",
          700: "hsl(var(--zhiman-primary-700))",
          800: "hsl(var(--zhiman-primary-800))",
          900: "hsl(var(--zhiman-primary-900))",
          950: "hsl(var(--zhiman-primary-950))",
        },
        secondary: {
          DEFAULT: "hsl(var(--zhiman-secondary))",
          foreground: "hsl(var(--zhiman-secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--zhiman-destructive))",
          foreground: "hsl(var(--zhiman-destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--zhiman-success))",
          foreground: "hsl(var(--zhiman-success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--zhiman-warning))",
          foreground: "hsl(var(--zhiman-warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--zhiman-info))",
          foreground: "hsl(var(--zhiman-info-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--zhiman-muted))",
          foreground: "hsl(var(--zhiman-muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--zhiman-accent))",
          foreground: "hsl(var(--zhiman-accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--zhiman-popover))",
          foreground: "hsl(var(--zhiman-popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--zhiman-card))",
          foreground: "hsl(var(--zhiman-card-foreground))",
        },
        surface: {
          50: "hsl(var(--zhiman-surface-50))",
          100: "hsl(var(--zhiman-surface-100))",
          200: "hsl(var(--zhiman-surface-200))",
          300: "hsl(var(--zhiman-surface-300))",
          400: "hsl(var(--zhiman-surface-400))",
          500: "hsl(var(--zhiman-surface-500))",
          600: "hsl(var(--zhiman-surface-600))",
          700: "hsl(var(--zhiman-surface-700))",
          800: "hsl(var(--zhiman-surface-800))",
          900: "hsl(var(--zhiman-surface-900))",
          950: "hsl(var(--zhiman-surface-950))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--zhiman-sidebar))",
          foreground: "hsl(var(--zhiman-sidebar-foreground))",
          primary: "hsl(var(--zhiman-sidebar-primary))",
          "primary-foreground": "hsl(var(--zhiman-sidebar-primary-foreground))",
          accent: "hsl(var(--zhiman-sidebar-accent))",
          "accent-foreground": "hsl(var(--zhiman-sidebar-accent-foreground))",
          border: "hsl(var(--zhiman-sidebar-border))",
          ring: "hsl(var(--zhiman-sidebar-ring))",
        },
        border: "hsl(var(--zhiman-border))",
        input: "hsl(var(--zhiman-input))",
        ring: "hsl(var(--zhiman-ring))",
        chart: {
          "1": "hsl(var(--zhiman-chart-1))",
          "2": "hsl(var(--zhiman-chart-2))",
          "3": "hsl(var(--zhiman-chart-3))",
          "4": "hsl(var(--zhiman-chart-4))",
          "5": "hsl(var(--zhiman-chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--zhiman-radius)",
        md: "var(--zhiman-radius-md)",
        sm: "var(--zhiman-radius-sm)",
        xl: "var(--zhiman-radius-xl)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        mono: [
          "JetBrains Mono",
          "Fira Code",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "shiny-text": "shiny-text 2s linear infinite",
        "shimmer": "shimmer 2s infinite",
        "thinking": "thinking var(--duration) infinite linear",
        "shine": "shine var(--duration) infinite linear",
        "indeterminate": "indeterminate 2s linear infinite",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "shiny-text": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "shimmer": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "thinking": {
          "0%": { backgroundPosition: "0% 0%" },
          "100%": { backgroundPosition: "-200% 200%" },
        },
        "shine": {
          "0%": { backgroundPosition: "0% 0%" },
          "50%": { backgroundPosition: "100% 100%" },
          "to": { backgroundPosition: "0% 0%" },
        },
        "indeterminate": {
          "0%": { transform: "translateX(-100%)" },
          "50%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      typography: {
        DEFAULT: {
          css: {
            "--tw-prose-body": "hsl(var(--zhiman-muted-foreground))",
            "--tw-prose-headings": "hsl(var(--zhiman-foreground))",
            "--tw-prose-lead": "hsl(var(--zhiman-muted-foreground))",
            "--tw-prose-links": "hsl(var(--zhiman-primary))",
            "--tw-prose-bold": "hsl(var(--zhiman-foreground))",
            "--tw-prose-counters": "hsl(var(--zhiman-muted-foreground))",
            "--tw-prose-bullets": "hsl(var(--zhiman-muted-foreground))",
            "--tw-prose-hr": "hsl(var(--zhiman-border))",
            "--tw-prose-quotes": "hsl(var(--zhiman-foreground))",
            "--tw-prose-quote-borders": "hsl(var(--zhiman-border))",
            "--tw-prose-captions": "hsl(var(--zhiman-muted-foreground))",
            "--tw-prose-code": "hsl(var(--zhiman-foreground))",
            "--tw-prose-pre-code": "hsl(var(--zhiman-muted-foreground))",
            "--tw-prose-pre-bg": "hsl(var(--zhiman-muted))",
            "--tw-prose-th-borders": "hsl(var(--zhiman-border))",
            "--tw-prose-td-borders": "hsl(var(--zhiman-border))",
          },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
  ],
}; 